"""Parameter search for Orbit Wars YAML presets.

This tool keeps the existing strategy workflow intact:

* start from a base preset YAML
* generate candidate presets by changing values under ``config``
* build each candidate into a standalone agent file
* evaluate it with the existing ``orbit_wars.eval.runner`` harness
* write ranked CSV/JSON output plus every candidate YAML

Example:

    python tools/search_params.py configs/ow_proto.yaml search_spaces/ow_proto_core.yaml \
        --opponent preset:ow_proto --mode random --samples 24 --games 10 -p 4 \
        --out runs/search-ow-proto-core
"""

from __future__ import annotations

import argparse
import csv
import datetime as dt
import itertools
import json
import random
import shutil
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from orbit_wars.eval.runner import MatchResult, run_matches  # noqa: E402
from tools import build_submission  # noqa: E402


@dataclass(frozen=True)
class Candidate:
    index: int
    name: str
    config: dict[str, Any]
    params: dict[str, Any]


@dataclass(frozen=True)
class CandidateResult:
    candidate: Candidate
    games: int
    wins: int
    draws: int
    losses: int
    winrate: float
    mean_reward_diff: float
    mean_final_score_diff: float | None
    match_path: str | None

    def sort_key(self) -> tuple[float, float, float]:
        score_diff = (
            self.mean_final_score_diff
            if self.mean_final_score_diff is not None
            else float("-inf")
        )
        return (self.winrate, score_diff, self.mean_reward_diff)


def load_yaml(path: str | Path) -> dict[str, Any]:
    data = yaml.safe_load(Path(path).read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError(f"{path} must contain a YAML mapping")
    return data


def extract_parameter_space(data: dict[str, Any]) -> dict[str, list[Any]]:
    """Accept either ``parameters:``, ``config:``, or a direct mapping."""
    if "parameters" in data:
        raw = data["parameters"]
    elif "config" in data:
        raw = data["config"]
    else:
        raw = {
            k: v
            for k, v in data.items()
            if k not in {"name", "description", "agent", "mode", "samples"}
        }
    if not isinstance(raw, dict):
        raise ValueError("search space must be a mapping of parameter -> values")

    space: dict[str, list[Any]] = {}
    for key, values in raw.items():
        if not isinstance(values, list) or not values:
            raise ValueError(f"search parameter '{key}' must be a non-empty list")
        space[str(key)] = list(values)
    if not space:
        raise ValueError("search space is empty")
    return space


def grid_combinations(space: dict[str, list[Any]]) -> list[dict[str, Any]]:
    keys = list(space)
    return [
        dict(zip(keys, values))
        for values in itertools.product(*(space[k] for k in keys))
    ]


def choose_parameter_sets(
    space: dict[str, list[Any]],
    *,
    mode: str,
    samples: int | None,
    seed: int | None,
) -> list[dict[str, Any]]:
    combos = grid_combinations(space)
    if mode == "grid":
        if samples is not None:
            return combos[: max(0, int(samples))]
        return combos

    rng = random.Random(0x5EAC0 if seed is None else int(seed))
    if samples is None:
        samples = min(24, len(combos))
    samples = max(0, min(int(samples), len(combos)))
    return rng.sample(combos, samples)


def make_candidate(
    base: dict[str, Any],
    params: dict[str, Any],
    *,
    index: int,
    prefix: str,
) -> Candidate:
    cfg = dict(base)
    base_config = dict(base.get("config") or {})
    base_config.update(params)
    cfg["config"] = base_config
    cfg["name"] = f"{prefix}_{index:03d}"
    cfg["description"] = (
        f"Generated by tools/search_params.py from {base.get('name', 'base')}. "
        f"Overrides: {json.dumps(params, sort_keys=True)}"
    )
    return Candidate(index=index, name=str(cfg["name"]), config=cfg, params=dict(params))


def build_from_config(preset_name: str, cfg: dict[str, Any]) -> str:
    """Render a built submission from an in-memory config mapping."""
    agent_name = cfg.get("agent")
    if agent_name not in build_submission.AGENT_MODULES:
        known = sorted(build_submission.AGENT_MODULES)
        raise ValueError(f"unknown agent class {agent_name!r}; known: {known}")

    parts: list[str] = [build_submission.render_header(preset_name, cfg)]
    modules = (
        build_submission.SHARED_MODULES
        + build_submission.AGENT_MODULES[str(agent_name)]
    )
    for mod_path in modules:
        rel = mod_path.relative_to(ROOT).as_posix()
        parts.append(f"\n# {'='*68}\n# inlined from {rel}\n# {'='*68}\n")
        parts.append(
            build_submission.strip_local_imports(
                mod_path.read_text(encoding="utf-8")
            )
        )
    parts.append("\n")
    parts.append(
        build_submission.render_adapter(
            str(agent_name),
            cfg.get("config") or {},
        )
    )
    return "".join(parts)


def write_candidate(candidate: Candidate, out_dir: Path) -> tuple[Path, Path]:
    yaml_path = out_dir / "candidates" / f"{candidate.name}.yaml"
    built_path = out_dir / "built" / f"{candidate.name}.py"
    yaml_path.parent.mkdir(parents=True, exist_ok=True)
    built_path.parent.mkdir(parents=True, exist_ok=True)

    yaml_path.write_text(
        yaml.safe_dump(candidate.config, sort_keys=False, allow_unicode=False),
        encoding="utf-8",
    )
    built_path.write_text(
        build_from_config(candidate.name, candidate.config),
        encoding="utf-8",
    )
    return yaml_path, built_path


def summarize_candidate(
    candidate: Candidate,
    results: list[MatchResult],
    *,
    match_path: Path | None,
) -> CandidateResult:
    games = len(results)
    wins = sum(1 for r in results if r.winner == "a")
    losses = sum(1 for r in results if r.winner == "b")
    draws = games - wins - losses
    winrate = (wins + 0.5 * draws) / games if games else 0.0
    mean_reward_diff = (
        sum(r.reward_a - r.reward_b for r in results) / games
        if games
        else 0.0
    )

    score_diffs: list[float] = []
    for r in results:
        if r.metrics_a is None or r.metrics_b is None:
            continue
        score_diffs.append(
            float(r.metrics_a.final_score - r.metrics_b.final_score)
        )
    mean_score_diff = (
        sum(score_diffs) / len(score_diffs)
        if score_diffs
        else None
    )
    return CandidateResult(
        candidate=candidate,
        games=games,
        wins=wins,
        draws=draws,
        losses=losses,
        winrate=winrate,
        mean_reward_diff=mean_reward_diff,
        mean_final_score_diff=mean_score_diff,
        match_path=str(match_path) if match_path else None,
    )


def result_row(result: CandidateResult) -> dict[str, Any]:
    return {
        "candidate": result.candidate.name,
        "rank": "",
        "winrate": f"{result.winrate:.6f}",
        "mean_final_score_diff": (
            "" if result.mean_final_score_diff is None
            else f"{result.mean_final_score_diff:.6f}"
        ),
        "mean_reward_diff": f"{result.mean_reward_diff:.6f}",
        "wins": result.wins,
        "draws": result.draws,
        "losses": result.losses,
        "games": result.games,
        "params": json.dumps(result.candidate.params, sort_keys=True),
        "match_path": result.match_path or "",
    }


def write_results(
    results: list[CandidateResult],
    *,
    out_dir: Path,
    top_k: int,
) -> list[CandidateResult]:
    ranked = sorted(results, key=lambda r: r.sort_key(), reverse=True)
    fields = [
        "rank",
        "candidate",
        "winrate",
        "mean_final_score_diff",
        "mean_reward_diff",
        "wins",
        "draws",
        "losses",
        "games",
        "params",
        "match_path",
    ]
    csv_path = out_dir / "results.csv"
    with csv_path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fields)
        writer.writeheader()
        for rank, result in enumerate(ranked, start=1):
            row = result_row(result)
            row["rank"] = rank
            writer.writerow(row)

    json_path = out_dir / "results.json"
    json_path.write_text(
        json.dumps(
            [
                {
                    **result_row(result),
                    "rank": rank,
                    "params": result.candidate.params,
                }
                for rank, result in enumerate(ranked, start=1)
            ],
            indent=2,
            ensure_ascii=False,
        )
        + "\n",
        encoding="utf-8",
    )

    if ranked:
        best = ranked[0].candidate
        (out_dir / "best.yaml").write_text(
            yaml.safe_dump(best.config, sort_keys=False, allow_unicode=False),
            encoding="utf-8",
        )
    top_dir = out_dir / "top"
    top_dir.mkdir(exist_ok=True)
    for rank, result in enumerate(ranked[: max(0, top_k)], start=1):
        src = out_dir / "candidates" / f"{result.candidate.name}.yaml"
        dst = top_dir / f"rank_{rank:02d}_{result.candidate.name}.yaml"
        if src.is_file():
            shutil.copyfile(src, dst)
    return ranked


def default_output_dir(base_config: Path) -> Path:
    stamp = dt.datetime.now(dt.timezone.utc).strftime("%Y%m%d-%H%M%S")
    return ROOT / "runs" / f"search-{base_config.stem}-{stamp}"


def run_search(args: argparse.Namespace) -> list[CandidateResult]:
    base_path = Path(args.base_config)
    space_path = Path(args.search_space)
    base = load_yaml(base_path)
    space = extract_parameter_space(load_yaml(space_path))
    params_list = choose_parameter_sets(
        space,
        mode=args.mode,
        samples=args.samples,
        seed=args.seed,
    )
    if not params_list:
        raise ValueError("no candidates selected")

    out_dir = Path(args.out) if args.out else default_output_dir(base_path)
    if not out_dir.is_absolute():
        out_dir = (ROOT / out_dir).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(base_path, out_dir / "base.yaml")
    shutil.copyfile(space_path, out_dir / "search_space.yaml")

    prefix = args.prefix or f"{base.get('name') or base_path.stem}_search"
    candidates = [
        make_candidate(base, params, index=i, prefix=prefix)
        for i, params in enumerate(params_list)
    ]

    results: list[CandidateResult] = []
    for i, candidate in enumerate(candidates, start=1):
        _, built_path = write_candidate(candidate, out_dir)
        if args.dry_run:
            print(f"[{i}/{len(candidates)}] generated {candidate.name}")
            continue

        match_path = out_dir / "matches" / f"{candidate.name}_matches.jsonl"
        print(
            f"[{i}/{len(candidates)}] evaluating {candidate.name} "
            f"vs {args.opponent}"
        )
        match_results = run_matches(
            agent_a=f"file:{built_path}",
            agent_b=args.opponent,
            n_games=args.games,
            base_seed=args.seed,
            parallel=args.parallel,
            balance_positions=not args.no_balance,
            episode_steps=args.episode_steps,
            output_path=match_path,
        )
        result = summarize_candidate(
            candidate,
            match_results,
            match_path=match_path,
        )
        results.append(result)
        print(
            f"    winrate={result.winrate:.1%} "
            f"W-L-D={result.wins}-{result.losses}-{result.draws} "
            f"score_diff={result.mean_final_score_diff}"
        )

    if args.dry_run:
        print(f"\nGenerated {len(candidates)} candidates -> {out_dir}")
        return []

    ranked = write_results(results, out_dir=out_dir, top_k=args.top_k)
    print(f"\nWrote search results -> {out_dir}")
    if ranked:
        best = ranked[0]
        print(
            "Best: "
            f"{best.candidate.name} winrate={best.winrate:.1%} "
            f"mean_score_diff={best.mean_final_score_diff} "
            f"params={json.dumps(best.candidate.params, sort_keys=True)}"
        )
    return ranked


def main() -> None:
    ap = argparse.ArgumentParser(
        description="Generate and evaluate parameter variants of a YAML preset."
    )
    ap.add_argument("base_config", help="base preset YAML, e.g. configs/ow_proto.yaml")
    ap.add_argument("search_space", help="YAML mapping of config parameters to lists")
    ap.add_argument("--opponent", default="preset:ow_proto",
                    help="opponent spec for evaluation (default: preset:ow_proto)")
    ap.add_argument("--mode", choices=["grid", "random"], default="random",
                    help="candidate selection mode (default: random)")
    ap.add_argument("--samples", type=int, default=None,
                    help="candidate count for random mode, or grid prefix length")
    ap.add_argument("--games", type=int, default=6,
                    help="games per candidate (default: 6)")
    ap.add_argument("-p", "--parallel", type=int, default=1,
                    help="parallel worker count for each candidate (default: 1)")
    ap.add_argument("--seed", type=int, default=None,
                    help="seed for candidate sampling and match seeds")
    ap.add_argument("--episode-steps", type=int, default=None,
                    help="optional max turn override for faster rough screens")
    ap.add_argument("--no-balance", action="store_true",
                    help="do not swap player positions during evaluation")
    ap.add_argument("--out", default=None,
                    help="output directory (default: runs/search-<base>-<time>)")
    ap.add_argument("--prefix", default=None,
                    help="candidate name prefix")
    ap.add_argument("--top-k", type=int, default=5,
                    help="copy top K candidate YAMLs into out/top (default: 5)")
    ap.add_argument("--dry-run", action="store_true",
                    help="only generate candidate YAML/Python files, no evaluation")
    args = ap.parse_args()
    run_search(args)


if __name__ == "__main__":
    main()
